### ISSUE TITLE
output empty file

### ISSUE THREAD

**Issue by immuneAI** [genemine/iread#1]
Hey, thanks for the tool.

I'm using human BAM files. with intron annotation files given with the tool. But I'm seeing a blank output. This is my BAM format

NB551151:9:HTK55BGX3:4:23504:2506:11492	355	chr1	19091	1	76M	=	19173	157	CCCCACTCATGCTTTTCCATGTTCTTTGGCCGCAGCAAGGCCGCTCTCACTGCAAAGTTAACTCTGATGCGTGTGT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEE	NH:i:3	HI:i:1	AS:i:149	nM:i:0	NM:i:0	MD:Z:76	jM:B:c,-1	jI:B:i,-1	RG:Z:e61a521e-ebf2-4e50-bb0b-2cbcfd343b50

**Comment by mgaglia81** [comment]
We had a similar issue and we found a couple of fixes. 
One that might apply to you is that the intron annotation file calls the chromosomes "1", "2" etc. but your file calls them 'chr1" etc. If you can reprint the bedfile substituting the chromosome names it should work. 
The other was that in the bam2intron script. The samtools view function on line 36 pulls out the reads that are located in the introns, filtering them by the MAPQ quality score (5th column in the SAM/BAM format) and ignoring all reads with scores under 255. 
"samtools view -b -q 255 -@ 20  -L $intronbed $bam > $umapbam"
I guess this makes sense with output from STAR, but some other alignment softwares (tophat2 for example) assign MAPQ values under 255, so it ignored all of our reads. We changed that line to 
"samtools view -b -q 50 -@ 20  -L $intronbed $bam > $umapbam"
because 50 is the score for unique mapping in Tophat2 and we got an output. Still need to figure out if it is reasonable though, so take this with a grain of salt.

**Comment by pavsol** [comment]
I had the same trouble and setting -q parameter at line 37 in bam2intron to 60 solved the issue. 60 is the value of uniquely mapped reads by Hisat2.
Thank you.

**Comment by genemine** [comment]
Hi all, thanks for pointing out these issues. It's likely that the issues result from read aligners. In our test, we used the BAM file from STAR, and other aligners such as tophat or hisat were not tested. I think the solution from venkataddala is great. I will fix this issue and prepare an updated release.

**Comment by genemine** [comment]
@venkataddala  @pavsol  @mgaglia81  Hi all, the latest version from 0.8.6 has included '-q' as an option for iread.py, which allows you to specify the value of -q to identify uniquely mapped reads. Hope it helps.
